export const data = [
  { id: 1, firstName: 'John', lastName: 'Doe', gender: 'Male', dateOfBirth: '1990-05-15', email: 'john.doe@example.com' },
  { id: 2, firstName: 'Jane', lastName: 'Smith', gender: 'Female', dateOfBirth: '1985-08-22', email: 'jane.smith@example.com' },
  { id: 3, firstName: 'Alice', lastName: 'Johnson', gender: 'Female', dateOfBirth: '1992-12-01', email: 'alice.johnson@example.com' },
  { id: 4, firstName: 'Bob', lastName: 'Williams', gender: 'Male', dateOfBirth: '1980-02-18', email: 'bob.williams@example.com' },
  { id: 5, firstName: 'Charlie', lastName: 'Brown', gender: 'Male', dateOfBirth: '1995-10-30', email: 'charlie.brown@example.com' },
  { id: 6, firstName: 'Eve', lastName: 'Davis', gender: 'Female', dateOfBirth: '1998-07-12', email: 'eve.davis@example.com' },
  { id: 7, firstName: 'Oscar', lastName: 'Miller', gender: 'Male', dateOfBirth: '1988-03-27', email: 'oscar.miller@example.com' },
  { id: 8, firstName: 'Sophia', lastName: 'Martinez', gender: 'Female', dateOfBirth: '1993-11-08', email: 'sophia.martinez@example.com' },
  { id: 9, firstName: 'John', lastName: 'Doe', gender: 'Male', dateOfBirth: '1990-05-15', email: 'john.doe@example.com' },
  { id: 10, firstName: 'Jane', lastName: 'Smith', gender: 'Female', dateOfBirth: '1985-08-22', email: 'jane.smith@example.com' },
  { id: 11, firstName: 'Alice', lastName: 'Johnson', gender: 'Female', dateOfBirth: '1992-12-01', email: 'alice.johnson@example.com' },
  { id: 12, firstName: 'Bob', lastName: 'Williams', gender: 'Male', dateOfBirth: '1980-02-18', email: 'bob.williams@example.com' },
  { id: 13, firstName: 'Charlie', lastName: 'Brown', gender: 'Male', dateOfBirth: '1995-10-30', email: 'charlie.brown@example.com' },
  { id: 14, firstName: 'Eve', lastName: 'Davis', gender: 'Female', dateOfBirth: '1998-07-12', email: 'eve.davis@example.com' },
  { id: 15, firstName: 'Oscar', lastName: 'Miller', gender: 'Male', dateOfBirth: '1988-03-27', email: 'oscar.miller@example.com' },
  { id: 16, firstName: 'Sophia', lastName: 'Martinez', gender: 'Female', dateOfBirth: '1993-11-08', email: 'sophia.martinez@example.com' },
  { id: 17, firstName: 'John', lastName: 'Doe', gender: 'Male', dateOfBirth: '1990-05-15', email: 'john.doe@example.com' },
  { id: 18, firstName: 'Jane', lastName: 'Smith', gender: 'Female', dateOfBirth: '1985-08-22', email: 'jane.smith@example.com' },
  { id: 19, firstName: 'Alice', lastName: 'Johnson', gender: 'Female', dateOfBirth: '1992-12-01', email: 'alice.johnson@example.com' },
  { id: 20, firstName: 'Bob', lastName: 'Williams', gender: 'Male', dateOfBirth: '1980-02-18', email: 'bob.williams@example.com' },
  { id: 21, firstName: 'Charlie', lastName: 'Brown', gender: 'Male', dateOfBirth: '1995-10-30', email: 'charlie.brown@example.com' },
  { id: 22, firstName: 'Eve', lastName: 'Davis', gender: 'Female', dateOfBirth: '1998-07-12', email: 'eve.davis@example.com' },
  { id: 23, firstName: 'Oscar', lastName: 'Miller', gender: 'Male', dateOfBirth: '1988-03-27', email: 'oscar.miller@example.com' },
  { id: 24, firstName: 'Sophia', lastName: 'Martinez', gender: 'Female', dateOfBirth: '1993-11-08', email: 'sophia.martinez@example.com' }
];

